// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Brand
{
    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public string Description { get; set; }

    public string LogoUrl { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}