// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Brand
{
    public int Brandid { get; set; }

    public string Brandname { get; set; }

    public string Description { get; set; }

    public string Logourl { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}