// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Category
{
    public int Categoryid { get; set; }

    public string Categoryname { get; set; }

    public string Imageurl { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}