// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Chatmessage
{
    public int Chatmessageid { get; set; }

    public int Senderid { get; set; }

    public int Receiverid { get; set; }

    public string Message { get; set; }

    public DateTime Sentat { get; set; }

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}