// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Order
{
    public int Orderid { get; set; }

    public int? Cartid { get; set; }

    public int? Userid { get; set; }

    public string Paymentmethod { get; set; }

    public string Billingaddress { get; set; }

    public string Orderstatus { get; set; }

    public DateTime Orderdate { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }

    public virtual ICollection<Uservoucher> Uservouchers { get; set; } = new List<Uservoucher>();
}