// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Payment
{
    public int Paymentid { get; set; }

    public int? Orderid { get; set; }

    public decimal Amount { get; set; }

    public DateTime Paymentdate { get; set; }

    public string Paymentstatus { get; set; }

    public virtual Order Order { get; set; }
}