// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Product
{
    public int Productid { get; set; }

    public string Productname { get; set; }

    public string Briefdescription { get; set; }

    public string Fulldescription { get; set; }

    public string Technicalspecifications { get; set; }

    public decimal Price { get; set; }

    public string Imageurl { get; set; }

    public int? Categoryid { get; set; }

    public int? Brandid { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<Cartitem> Cartitems { get; set; } = new List<Cartitem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Productvoucher> Productvouchers { get; set; } = new List<Productvoucher>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}