// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Productimage
{
    public int Imageid { get; set; }

    public int Productid { get; set; }

    public string Imageurl { get; set; }

    public bool Isprimary { get; set; }

    public virtual Product Product { get; set; }
}