// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string BriefDescription { get; set; }

    public string FullDescription { get; set; }

    public string TechnicalSpecifications { get; set; }

    public decimal Price { get; set; }

    public string ImageUrl { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductVoucher> ProductVouchers { get; set; } = new List<ProductVoucher>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}