// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Productvoucher
{
    public int Productvoucherid { get; set; }

    public int Voucherid { get; set; }

    public int Productid { get; set; }

    public virtual Product Product { get; set; }

    public virtual Voucher Voucher { get; set; }
}