// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Productreview
{
    public int Reviewid { get; set; }

    public int Productid { get; set; }

    public int Userid { get; set; }

    public short Rating { get; set; }

    public string Comment { get; set; }

    public DateTime Createdat { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}