// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Uservoucher
{
    public int Uservoucherid { get; set; }

    public int Userid { get; set; }

    public int Voucherid { get; set; }

    public bool Isused { get; set; }

    public DateTime? Usedat { get; set; }

    public int? Orderid { get; set; }

    public DateTime Assignedat { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}