// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Userdevicetoken
{
    public int Tokenid { get; set; }

    public int Userid { get; set; }

    public string Fcmtoken { get; set; }

    public bool Isactive { get; set; }

    public DateTime Lastupdateddate { get; set; }

    public virtual User User { get; set; }
}