// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class User
{
    public int Userid { get; set; }

    public string Username { get; set; }

    public string Passwordhash { get; set; }

    public string Email { get; set; }

    public string Phonenumber { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public string Avatarurl { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Chatmessage> ChatmessageReceivers { get; set; } = new List<Chatmessage>();

    public virtual ICollection<Chatmessage> ChatmessageSenders { get; set; } = new List<Chatmessage>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Productreview> Productreviews { get; set; } = new List<Productreview>();

    public virtual ICollection<Userdevicetoken> Userdevicetokens { get; set; } = new List<Userdevicetoken>();

    public virtual ICollection<Uservoucher> Uservouchers { get; set; } = new List<Uservoucher>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}