// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Voucher
{
    public int Voucherid { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public decimal? Discountpercent { get; set; }

    public decimal? Discountamount { get; set; }

    public DateTime Startdate { get; set; }

    public DateTime Enddate { get; set; }

    public bool Isactive { get; set; }

    public virtual ICollection<Productvoucher> Productvouchers { get; set; } = new List<Productvoucher>();

    public virtual ICollection<Uservoucher> Uservouchers { get; set; } = new List<Uservoucher>();
}