// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductSaleApp.Repository.Models;

public partial class Wishlist
{
    public int Wishlistid { get; set; }

    public int Userid { get; set; }

    public int Productid { get; set; }

    public DateTime Createdat { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}